
POST http://localhost:5140/user
Content-Type: application/json

{
  "username": "Penny",
  "password": "hunter1",
  "role": "Admin"
}

###
# @name Login
POST http://localhost:5140/user/login
Content-Type: application/json

{
  "username": "Penny",
  "password": "hunter1"
}

###
GET http://localhost:5140/user
Content-Type: application/json


###

POST http://localhost:5140/pets
Content-Type: application/json
Authorization: Bearer {{Login.response.body.token}}

{
  "name": "Fluffy",
  "spriteId": 1
}

