
POST http://localhost:5140/user
Content-Type: application/json

{
  "username": "Penny2",
  "password": "hunter3",
  "petSpriteId": 2
}

###

POST http://localhost:5140/user/login
Content-Type: application/json

{
  "username": "Penny2",
  "password": "hunter3"
}

